import Foundation
import WebKit

@MainActor
public final class PDFReportGenerator {
    public init() {}

    public func generateReport(assets: [MonitoredAsset], findings: [Finding]) async throws -> Data {
        let html = buildHTML(assets: assets, findings: findings)
        let webView = WKWebView(frame: NSRect(x: 0, y: 0, width: 612, height: 792))
        webView.loadHTMLString(html, baseURL: nil)

        // Wait for content to load
        try await Task.sleep(for: .seconds(1))

        let config = WKPDFConfiguration()
        config.rect = CGRect(x: 0, y: 0, width: 612, height: 792)

        return try await webView.pdf(configuration: config)
    }

    private func buildHTML(assets: [MonitoredAsset], findings: [Finding]) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short

        var html = """
            <!DOCTYPE html>
            <html><head><style>
            body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #1a1a1a; border-bottom: 2px solid #007AFF; padding-bottom: 8px; }
            h2 { color: #555; margin-top: 24px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; }
            th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background: #f5f5f7; font-weight: 600; }
            .safe { color: #34C759; }
            .exposed { color: #FF3B30; }
            .unknown { color: #8E8E93; }
            .meta { color: #888; font-size: 12px; margin-top: 32px; }
            </style></head><body>
            <h1>Canary Security Report</h1>
            <p>Generated: \(dateFormatter.string(from: Date()))</p>

            <h2>Monitored Assets (\(assets.count))</h2>
            <table>
            <tr><th>Type</th><th>Asset</th><th>Status</th><th>Findings</th><th>Last Checked</th></tr>
            """

        for asset in assets {
            let lastChecked = asset.lastChecked.map { dateFormatter.string(from: $0) } ?? "Never"
            html += """
                <tr>
                <td>\(asset.kind.rawValue.capitalized)</td>
                <td>\(asset.label)</td>
                <td class="\(asset.status.rawValue)">\(asset.status.rawValue.capitalized)</td>
                <td>\(asset.findingCount)</td>
                <td>\(lastChecked)</td>
                </tr>
                """
        }

        html += "</table>"

        if !findings.isEmpty {
            html += """
                <h2>Findings (\(findings.count))</h2>
                <table>
                <tr><th>Source</th><th>Title</th><th>Severity</th><th>Date</th></tr>
                """

            for finding in findings {
                html += """
                    <tr>
                    <td>\(finding.source.rawValue)</td>
                    <td>\(finding.title)</td>
                    <td>\(finding.severity.rawValue.capitalized)</td>
                    <td>\(dateFormatter.string(from: finding.date))</td>
                    </tr>
                    """
            }

            html += "</table>"
        }

        html += """
            <p class="meta">Report generated by Canary — macOS Breach Monitor</p>
            </body></html>
            """

        return html
    }
}
